steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/rapid-jaguar-prisma/dockertest:$SHORT_SHA', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/rapid-jaguar-prisma/dockertest:$SHORT_SHA']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['beta', 'run', 'deploy', 'dockertest', '--image=gcr.io/rapid-jaguar-prisma/dockertest:$TAG_NAME', '--region=us-central1', '--platform']